version: '3'
services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret_cookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq1'
    ports:
      - "15672:15672"
      - "5672:5672"

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret_cookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq2'
    links:
      - rabbitmq1
    depends_on:
      - rabbitmq1

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret_cookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq3'
    links:
      - rabbitmq1
      - rabbitmq2
    depends_on:
      - rabbitmq1
      - rabbitmq2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5672:5672"

  order_service:
    build: ./order_service
    ports:
      - "3001:3001"
    environment:
      - RABBITMQ_HOST=nginx

  worker_service:
    build: ./worker_service
    depends_on:
      - nginx
    environment:
      - RABBITMQ_HOST=nginx
    deploy:
      replicas: 3
